version: '3'
services:
  app:
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      AWS_ACCESS_KEY_ID: no_key_needed
      AWS_SECRET_ACCESS_KEY: no_key_needed
      DDB_HOST: db
  db:
    container_name: db
    image: amazon/dynamodb-local
    restart: always
    ports:
        - "8000:8000"
